apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.dockerConfig.value }}
kind: Secret
metadata:
  creationTimestamp: "2023-02-14T22:47:08Z"
  name: regcred
  namespace: {{ .Values.namespace.name }}
  resourceVersion: "23564"
  uid: ea440e84-c53b-40de-ba4e-9db01ae7d0a9
type: kubernetes.io/dockerconfigjson