namespace:
  name: value

deploymentName: value

repositoryURL: value

dockerConfig:
  value: value

image:
  name: value
  tag: value

secretName: value

data:
  server: value
  userName: value
  password: value